### ISSUE TITLE
Specifying a mod loader does not change the list of mods

### ISSUE THREAD

**Issue by kuylar** [kuylar/curserinth#1]
`https://curserinth-api.kuylar.dev/v2/search?limit=20&index=relevance&facets=[[%22categories:fabric%22],[%22project_type:mod%22]]` returns the following output
![image](https://user-images.githubusercontent.com/52961639/184990236-fa1eb79e-bd81-41a5-bdc4-5f9a5dbaa093.png)
If the same request is done with the project type being `modpack`, the response does not change

**Comment by kuylar** [comment]
Made sure that the call to the CF API is done correctly, but the response is still the same

**Comment by Defetyre** [comment]
It's still a thing, and it renders your website useless when searching for fabric mods
