### ISSUE TITLE
Some searches with numbers cannot find projects

### ISSUE THREAD

**Issue by Justsnoopy30** [kuylar/curserinth#11]
Also, searches with spaces on the end cannot find anything.

Screenshots:
Searching "All the Mods"
![image](https://user-images.githubusercontent.com/33374736/232344211-7af2eb28-7290-41b0-b7b0-7e71c9d4fef0.png)

Searching "All the Mods 8"
![image](https://user-images.githubusercontent.com/33374736/232344229-8cdbdca3-93d9-48ef-9723-d0f17a7955a1.png)

**Comment by kuylar** [comment]
The first part is a bug on CurseForge's side, and I can't do much about it.

| Normal Search | Search with # on end |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/52961639/232377483-288a3511-da46-469b-a1e1-a82326ba67cd.png) | ![image](https://user-images.githubusercontent.com/52961639/232377490-9cb16197-b8b8-4cb2-8846-a12dd486483a.png) |


the second part is on my I'm on it right now
